### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by smeng9** [flexivrobotics/flexiv_rdk#14]
Python 3.10 has been released for more than 1 year, do we have any timelines to update the targeted python version?

**Comment by pzhu-flexiv** [comment]
Which OS are you using?

> Python 3.10 has been released for more than 1 year, do we have any timelines to update the targeted python version?

**Comment by pzhu-flexiv** [comment]
Python 3.10 support will be added to the upcoming release 0.7 for all supported OS.
