### ISSUE TITLE
[BUG] Gravity compensation cannot turn off

### ISSUE THREAD

**Issue by acf986** [flexivrobotics/flexiv_rdk#39]
**Version information**
- RDK: v0.8
- Robot software: v2.10.5
- OS: Ubuntu 20.04 - x86_64

**Describe the bug**
streamJointTorque(tau, false) does not turn off gravity compensation

**Steps to reproduce**
1. Set the gravity compensation flag of streamJointTorque to false.
2. Run a simple controller like tau = -10 * q_dot;

**Expected behavior**
The robot arm will drop because of the lack of gravity compensation.

**Additional context**
We have tried turn the gravity compensation flag on/off, but it seems there is no effect on the robot arm control at all.

**Comment by pzhu-flexiv** [comment]
@acf986 This is a known issue and has been fixed in the upcoming RDK v0.9 release.

**Comment by pzhu-flexiv** [comment]
Fixed with release #40.
