### ISSUE TITLE
关节4范围

### ISSUE THREAD

**Issue by XieShaosong** [flexivrobotics/flexiv_rdk#4]
https://github.com/flexivrobotics/flexiv_rdk/blob/a83755ab7be603eefbe92dfcd5c47060c9a12914/spec/flexiv_rizon4_kinematics.urdf#L32

产品说明书上关节4范围： A4：-154°至+107°

请问应该参照哪个标准？

**Comment by pzhu-flexiv** [comment]
There was an update to the User Manual on joint ranges a few months ago, please request the latest User Manual from sales, thank you.
![image](https://user-images.githubusercontent.com/34045850/148131994-4c230c41-2510-4c5f-9fc7-3787173ea843.png)
