### ISSUE TITLE
[FEATURE] Set tools

### ISSUE THREAD

**Issue by acf986** [flexivrobotics/flexiv_rdk#43]
**Is your feature request related to a problem? Please describe.**
We have installed a tool changer and can switch between multiple tools. All the used tools are added in the elements. How can we select which tool is being currently used through the RDK API?

**Describe the solution you'd like**
A function to set the currently using tool by name.

**Describe alternatives you've considered**
I noticed the primitives seems to support the use of different tools, is it possible to access that option when sending primitives through the RDK?

**Additional context**
NA

**Comment by pzhu-flexiv** [comment]
@acf986 Unfortunately RDK v0.x is not able to do online tool switch, but RDK v1.x supports this feature. See https://github.com/flexivrobotics/flexiv_rdk/blob/v1.x/example/basics8_update_robot_tool.cpp

However, to use RDK v1.x, you would need to upgrade your robot software from release track to beta track.
