### ISSUE TITLE
[BUG] wrong version in python rdk

### ISSUE THREAD

**Issue by Valen-C12** [flexivrobotics/flexiv_rdk#53]
Not sure if it is because the version text is not updated but the so file is correct 1.4 version, or the so file is just old one. Please investigate. It will be better if there are a way for the user to check the real version of the so file, not only from the log text.

**Version information**
- RDK: v1.4
- Robot software: not related
- OS: macOS 14.4.1 (23E224), M2

**Describe the bug**
![image](https://github.com/flexivrobotics/flexiv_rdk/assets/123928892/16898667-4943-464f-b924-e10bd80db0c3)

**Steps to reproduce**
run the example py file

**Expected behavior**
the version displayed should be same with the running one

**Screenshots**
![image](https://github.com/flexivrobotics/flexiv_rdk/assets/123928892/72ae41fc-4998-469b-ba7f-f75c96300813)

**Additional context**
Not sure if it is because the version text is not updated but the so file is correct 1.4 version, or the so file is just old one. Please investigate. It will be better if there are a way for the user to check the real version of the so file, not only from the log text.

**Comment by pzhu-flexiv** [comment]
@Valen-C12 The release/xxx branch is a development-in-progress branch and should not be considered complete until officially released. Normally, release/xxx branch will only be updated with Ubuntu x86_64 libs for internal evaluation. libs for other OS are not updated until the actual release happens.
