### ISSUE TITLE
Allow Joint Freedrive Floating from RDK

### ISSUE THREAD

**Issue by joepuzzo** [flexivrobotics/flexiv_rdk#55]
Currently I can enable freedrive floating via

```js
executePrimitive(
            f"FloatingCartesian(cartFloatingAxis={floatingAxis}, cartFloatingFrame={cartFloatingFrame}, enableJointFloating={enableJointFloating})"
        )
```

But I would really also love the ability to enable freedrive floating for individual joints as well. Is there a `FloatingJoint` function hidden away somewhere ? :)

**Comment by pzhu-flexiv** [comment]
@joepuzzo What software version are you using?

**Comment by joepuzzo** [comment]
For RDK im using 0.10

**Comment by pzhu-flexiv** [comment]
@joepuzzo Try primitive `floatingSoft`. It has the following parameters:
- `jointFloatingSwitch`: switch for each joint floating, 0 for off, 1 for on. Data type: Vector7d. Default value: 1.0 1.0 1.0 1.0 1.0 1.0 1.0
- `dampScale`: scale of joint damping. Data type: double. Range: 1.0 - 10.0. Default value: 1.0.

**Comment by joepuzzo** [comment]
<img width="908" alt="Screenshot 2024-06-04 at 6 19 01 AM" src="https://github.com/flexivrobotics/flexiv_rdk/assets/9516899/e13352dc-b5fd-4dd5-8d14-63290ae19b50">

Seems that does not exist

**Comment by pzhu-flexiv** [comment]
@joepuzzo It's floatingSoft not FloatingSoft

**Comment by joepuzzo** [comment]
Oh wow I just guessed because "FloatingCartesian" is uppercase that `floatingSoft` would also be uppercase haha

**Comment by joepuzzo** [comment]
Will give it a try now

**Comment by joepuzzo** [comment]
That worked! Thanks!

**Comment by yellownebula10** [comment]
@pzhu-flexiv I would like to use the primitives `FloatingCartesian` and `floatingSoft` in my application, but they do not seem to be mentioned in the [primitives documentation](https://original.flexiv.com/en/primitives/index.html#flexiv-primitives-manual). Where can I find documentation for these primitives?

**Comment by kaibiao-flexiv** [comment]
Hi @yellownebula10, `FloatingCartesian` and `floatingSoft` are not standard primitives, and therefore not documented on our primitives page. If you are interested, you can import [PLAN-FreeDriveAuto.zip](https://github.com/user-attachments/files/16059135/PLAN-FreeDriveAuto.zip) on Elements and check out these primitives' parameters and descriptions.
