### ISSUE TITLE
Ability to Jog Robot via RDK

### ISSUE THREAD

**Issue by joepuzzo** [flexivrobotics/flexiv_rdk#56]
I would love if there were a a primitive that would allow me to jog the robot. Currently I can achieve this by looking at current cart pos or joint pos and only modify the field I want, however it would be pretty sweet if this was a built in function.

**Comment by pzhu-flexiv** [comment]
@joepuzzo Joint jogging can be easily achieved using `NRT_JOINT_POSITION` control mode.

**Comment by joepuzzo** [comment]
IS there example of executing jog via this control mode in RDK ?

**Comment by pzhu-flexiv** [comment]
@pzhu-flexiv Not on joint jogging specifically, but [this example](https://github.com/flexivrobotics/flexiv_rdk/blob/main/example_py/intermediate1_non_realtime_joint_position_control.py) should give you the idea.
