### ISSUE TITLE
[FEATURE] Support for Dynamically Updating Trajectories

### ISSUE THREAD

**Issue by isa-9** [flexivrobotics/flexiv_rdk#57]
**Describe the solution you'd like**
I would like to be able to modify the .traj file and/or .flex file using third-party software, then execute a plan in FlexivRDK that uses the Grind primitive with the "fileName" parameter set to the updated .traj file, without having to go through Flexiv Elements. This would let us to maintain the same plan flow while using a variable trajectory.

**Describe alternatives you've considered**
As an alternative, we have considered manually updating the trajectory within Flexiv Elements, but this approach is not efficient for dynamic adjustments.

**Comment by pzhu-flexiv** [comment]
@isa-9 Are you looking for something like this?
https://github.com/flexivrobotics/flexiv_rdk/blob/release/v1.4/include/flexiv/rdk/file_io.hpp#L42

RDK v1.4 should be available late June / early July.
