### ISSUE TITLE
Modification of workpiece coordinates

### ISSUE THREAD

**Issue by isa-9** [flexivrobotics/flexiv_rdk#58]
In Flexiv Elements, it is possible to configure new workpieces coordinates or change them. Is it possible to create a new workpiece coordinate or to modify one with RDK (without using Flexiv Elements) ?

**Comment by pzhu-flexiv** [comment]
@isa-9 Hi, this function is not currently available in RDK, it will be added in release v1.5.

**Comment by pzhu-flexiv** [comment]
https://github.com/flexivrobotics/flexiv_rdk/blob/main/include/flexiv/rdk/work_coord.hpp
