### ISSUE TITLE
[BUG] get global var of COORD ARRAY type via rdk will be truncated at 127 length

### ISSUE THREAD

**Issue by Valen-C12** [flexivrobotics/flexiv_rdk#61]
**Version information**
- RDK: 0.10
- Robot software: v2.11.5
- OS: MacOS 14.5, Apple M2

**Describe the bug**
Look at the 'contact_points', the element shows it contain 7 coord points, but in value get via rdk, the value is truncated

![20240624-145325](https://github.com/flexivrobotics/flexiv_rdk/assets/123928892/28b65209-e313-42fb-a5fb-bc94dfd708a6)
![20240624-145334](https://github.com/flexivrobotics/flexiv_rdk/assets/123928892/e0e3dc26-3356-44be-b6b8-b079122b96ce)

**Steps to reproduce**
1. store a global var of coord array type with more than 2 points via element ui
2. use rdk to get the global vars
3. See error

**Expected behavior**
The global vars get via rdk should be full and no any truncated

**Comment by pzhu-flexiv** [comment]
@Valen-C12 Hello, this bug no longer exists in RDK v1.4, which is expected to be released early next month. Below shows getting and printing 2 global variables. The first contains 7 ARRAY_COORD points, the second contains 20  ARRAY_COORD points. Both are complete.
![image](https://github.com/flexivrobotics/flexiv_rdk/assets/34045850/746e57cd-c9b8-4f95-96a5-47d083b4d228)

**Comment by Valen-C12** [comment]
@pzhu-flexiv Nice to hear that, looking forward to the new version
