### ISSUE TITLE
[FEATURE] Get positions of user defined reference frames

### ISSUE THREAD

**Issue by isa-9** [flexivrobotics/flexiv_rdk#63]
**Describe the solution you'd like**
I would like to get (with RDK) the TCP pose relative to a specific workpiece/reference frame that was created in Flexiv Elements or to get all of the workpiece coordinates that were created in Flexiv Elements.

**Comment by pzhu-flexiv** [comment]
@isa-9 Interacting with workpiece coordinate will be added in RDK v1.5.

**Comment by pzhu-flexiv** [comment]
https://github.com/flexivrobotics/flexiv_rdk/blob/main/include/flexiv/rdk/work_coord.hpp
