### ISSUE TITLE
[BUG] Repeatably attempting to connect to a Rizon 10 by creating a flexivrdk.Robot while the controler is still bootin causes the controller to never boot.

### ISSUE THREAD

**Issue by skyrimax** [flexivrobotics/flexiv_rdk#75]
**Version information**
- RDK: v0.10
- Robot softwarepackage:v2.11.5
- OS: L4T 5.10.104-tegra, arm64v8

**Describe the bug**
Repeatably attempting to connect to a Rizon 10 by creating a flexivrdk.Robot while the controler is still bootin causes the controller to never boot. We waited well over 10 minutes.

**Steps to reproduce**
Here is simple python script that should allow you to reproduce the issue
```
import flexivrdk

robot_ip_addr = 'ENTER YOUR ROBOT IP HERE'
local_ip_addr = 'ENTER YOUR LOCAL IP HERE

while True:
    try:
        robot = flexivrdk.Robot(robot_ip_addr, local_ip_addr)
        logger.info('Connected to Barry robot')
        break
    except Exception as e:
        logger.warning(f'Caught {type(e)} while attempting to connect to Barry robot: {e}, retrying in 5s')
        await asyncio.sleep(5)
        continue
```

1. Unplug/switch off the controller
2. Start the above pyhton script
3. Plug/switch on the controller
4. Wait
5. The controller never completelly boots and the connection is never established

**Expected behavior**
We would expect the controller the controller to boot normally and the RDK to connect once the controller is ready

**Additional context**
We don't think this has an influence, but out script runs in a docker container with the priviledged flag enabled.

**Comment by dajun-flexiv** [comment]
Hi,

This behavior was later fixed in RDK v1.4. I have just tested it on v1.4 and it was working. Unfortunately, v1.4 is not compatible with the currently released robot firmware v2.11.5. I will keep you updated on future robot firmware releases. Sorry for the inconvenience.

![image](https://github.com/user-attachments/assets/901703f9-470d-435c-9663-cf2739205bce)
